/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, IsDate, ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { PrivacyUpdateManyWithoutUsersInput } from "./PrivacyUpdateManyWithoutUsersInput";
import { ProfileUpdateManyWithoutUsersInput } from "./ProfileUpdateManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { SettingsUpdateManyWithoutUsersInput } from "./SettingsUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  lastLogin?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
    type: () => PrivacyUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => PrivacyUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => PrivacyUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  privacies?: PrivacyUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => ProfileUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ProfileUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ProfileUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  profiles?: ProfileUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => SettingsUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SettingsUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SettingsUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  settingsItems?: SettingsUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  sub?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;
}

export { UserUpdateInput as UserUpdateInput };
